# Arithmetic operation

#    operation                     function   
## 1. A+B-------------------------np.add(A,B)
## 2. A-B-------------------------np.substarct(A,B)
## 3. A*B-------------------------np.multiply(A,B)
## 4. A/B-------------------------np.divide(A,B)
## 5. A%B-------------------------np.mod(A,B)
## 6. A**B------------------------np.power(A,B)
## 7. 1/A-------------------------np.reciprocal(A)


In [1]:
import numpy as np 
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,7])


### 1. Add

In [21]:
add1=arr1+arr2
print(add1)

[ 4  6  8 10 12]


In [22]:
add2=np.add(arr1,arr2)
print(add2)

[ 4  6  8 10 12]


### 2. substract

In [23]:
sub1=arr1-arr2
print(sub1)

[-2 -2 -2 -2 -2]


In [24]:
sub2=np.subtract(arr1,arr2)
print(sub2)

[-2 -2 -2 -2 -2]


### 3. Multiply

In [25]:
mul1=arr1*arr2
print(mul1)

[ 3  8 15 24 35]


In [26]:
mul2=np.multiply(arr1,arr2)
print(mul2)

[ 3  8 15 24 35]


### 4. Divide

In [27]:
div1 =arr1/arr2
print(div1)

[0.33333333 0.5        0.6        0.66666667 0.71428571]


In [28]:
div2=np.divide(arr1,arr2)
print(div2)

[0.33333333 0.5        0.6        0.66666667 0.71428571]


### 5. Modulo

In [29]:
mod1=arr1%arr2
print(mod1)

[1 2 3 4 5]


In [30]:
mod2=np.mod(arr1,arr2)
print(mod2)

[1 2 3 4 5]


### 6. Power

In [31]:
pov1=arr1**arr2
print(pov1)

[    1    16   243  4096 78125]


In [32]:
pov2=np.power(arr1,arr2)
print(pov2)

[    1    16   243  4096 78125]


### 7. Inverse or resiprocal

In [33]:
res1=1/arr1
print(res1)

[1.         0.5        0.33333333 0.25       0.2       ]


In [34]:
res2=np.reciprocal(arr1)
print(res2)

[1 0 0 0 0]


# Arithmetic function

## 1. np.min(x)-----------------------  find minimum element from array
## 2. np.max(x)-----------------------  find maximum element from array 
## 3. np.argmin/max(x)----------------  find address of min or max element
## 4. np.sqrt(x)----------------------  find squreroot of each value of array
## 5. np.sin(x)-----------------------  find sin value of each element
## 6. np.cos(x)-----------------------  find cos value of each element
## 7. np.cumsum(x)--------------------  adds vext value in element expect index 0

In [16]:
x=np.array([1,2,3,4,5,6,7])

print('minimum element:',np.min(x))
print('maximum element:',np.max(x))
print('mimimmum element address:',np.argmin(x))
print('squreroot :',np.sqrt(x))
print('sin value',np.sin(x))
print('cos value:',np.cos(x))
print('cumsum:',np.cumsum(x))

minimum element: 1
maximum element: 7
mimimmum element address: 0
squreroot : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]
sin value [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]
cos value: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225]
cumsum: [ 1  3  6 10 15 21 28]


# Brodcasting numpy Arrays

## when it happens
if array diamention is different you cna see example below

In [4]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3])
print(a+b)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

#  rules for this
## 1. same diamention
## 2. compare array dimention its has atleast 1 or same

In [5]:
c=np.array([[[1],[3],[2]]])
print(b+c)

[[[2 3 4]
  [4 5 6]
  [3 4 5]]]
