# array creation

In [55]:
import numpy as np
list1=[1,2,3,4,5,6]
arr=np.array(list1)
print(arr)

[1 2 3 4 5 6]


# 2D array & 3D array

In [56]:
list2=[list1]
arr2=np.array(list2)
list3=[list2]
arr3=np.array(list3)
print(arr2)
print(arr3)

[[1 2 3 4 5 6]]
[[[1 2 3 4 5 6]]]


# multiple dimention array

In [57]:
arr4=np.array(list1,ndmin=10)
print(arr4)

[[[[[[[[[[1 2 3 4 5 6]]]]]]]]]]


#  check array dimention

In [58]:
print(np.ndim(arr4))

10


# create array of zeross

In [59]:
arr5=np.zeros((4,4))
print(arr5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# create array of onces

In [60]:
arr6=np.ones((4,5))
print(arr6)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# empty array

In [61]:
arr7=np.empty((4,5))
print(arr7)                     #it copy privious if same dimention passed

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# range array

In [62]:
arr8=np.arange(4)
print(arr8)

[0 1 2 3]


# identity matrix or only diagonal element array

In [63]:
arr9=np.eye(4,5)
print(arr9)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# linspace funtion makes same spaced array

In [64]:
arr10=np.linspace(0,20, num=5)
print(arr10)

[ 0.  5. 10. 15. 20.]


# random number array creation

# rand() function
generate values between 0 to 1

In [65]:
# generate values between 0 to 1
ran1=np.random.rand(4)
print(ran1)

[0.27302092 0.69639797 0.09472186 0.4470916 ]


In [66]:
ran2=np.random.rand(3,3)
print(ran2)

[[0.11028583 0.47062169 0.45217641]
 [0.14108155 0.00091206 0.12124367]
 [0.61235744 0.018173   0.40528647]]


# randn() function
generate number near to zero

In [67]:
ran3=np.random.randn(4)
print(ran3)

[-0.26368681  0.76942117 -1.73403357  0.23086973]


In [68]:
ran4=np.random.randn(3,3)
print(ran4)

[[ 0.16700604 -0.6493759  -1.26244777]
 [-0.78714961 -1.86153308 -0.81312241]
 [ 0.0327166  -0.31565228 -0.59439276]]


# ranf() function
generate value between 0.0 to 1.0 but it excludes 1

In [69]:
ran5=np.random.ranf(4)
print(ran5)

[0.21027403 0.90826531 0.42864759 0.43301544]


# randint(min,max,total value) function
it generates randon integer between given range

In [76]:
ran6=np.random.randint(5,20,5)
print(ran6)

[12 13  5  6 19]
