# Indexing
## 1D
## 2D
## 3D

In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print('array:',arr1)
print('dia:',arr1.ndim)
print('geting 3:',arr1[2])

array: [1 2 3 4 5]
dia: 1
geting 3: 3


In [8]:
arr2=np.array([[1,2],[4,5]])
print('array:\n',arr2)
print('dia:',arr2.ndim)
print('geting 4:',arr2[1,0])

array:
 [[1 2]
 [4 5]]
dia: 2
geting 4: 4


In [7]:
arr3=np.array([[[1,2,3],[4,5,6]]])
print('array:\n',arr3)
print('dia:',arr3.ndim)
print('geting 3:',arr3[0,0,2])

array:
 [[[1 2 3]
  [4 5 6]]]
dia: 3
geting 3: 3


# Slicing
## variable[start:stop:step]
its also itrate n-1 index <br>
1.from start  to stop= variable[ : stop]<br>
2. from start to end=[start:] <br>
3.steps=[::step]

In [9]:
print(arr1[1:5])
print(arr2[1,1:])
print(arr3[0,1,1:])

[2 3 4 5]
[5]
[5 6]


# Iteration
for  iteration in normal way we have to use lops in multidimentional arrary we have tu use multiple nested loops.in pumpy we have inbuild function that iterate wihout loops.<br>
### 1.np.nditen():<br>
    it iterate array and is also can change data type for changinginng data type we have to provide np.nditen(var,flag='buffered',op_dtype='f')
### <br>2.np.enumurate():<br>
    it iterate array and give positin and data also.in this we have to use loop for printing 

In [17]:
for i in np.nditer(arr3,flags=['buffered'],op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')


In [19]:
for j,d in np.enumerate(arr3):
    print(j,d)

AttributeError: module 'numpy' has no attribute 'enumerate'