# Indexing
## 1D
## 2D
## 3D

In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print('array:',arr1)
print('dia:',arr1.ndim)
print('geting 3:',arr1[2])

array: [1 2 3 4 5]
dia: 1
geting 3: 3


In [2]:
arr2=np.array([[1,2],[4,5]])
print('array:\n',arr2)
print('dia:',arr2.ndim)
print('geting 4:',arr2[1,0])

array:
 [[1 2]
 [4 5]]
dia: 2
geting 4: 4


In [3]:
arr3=np.array([[[1,2,3],[4,5,6]]])
print('array:\n',arr3)
print('dia:',arr3.ndim)
print('geting 3:',arr3[0,0,2])

array:
 [[[1 2 3]
  [4 5 6]]]
dia: 3
geting 3: 3


# Slicing
## variable[start:stop:step]
its also itrate n-1 index <br>
1.from start  to stop= variable[ : stop]<br>
2. from start to end=[start:] <br>
3.steps=[::step]

In [4]:
print(arr1[1:5])
print(arr2[1,1:])
print(arr3[0,1,1:])

[2 3 4 5]
[5]
[5 6]


# Iteration
for  iteration in normal way we have to use lops in multidimentional arrary we have tu use multiple nested loops.in pumpy we have inbuild function that iterate wihout loops.<br>
### 1.np.nditen():<br>
    it iterate array and is also can change data type for changinginng data type we have to provide np.nditen(var,flag='buffered',op_dtype='f')
### <br>2.np.enumurate():<br>
    it iterate array and give positin and data also.in this we have to use loop for printing 

In [5]:
for i in np.nditer(arr3,flags=['buffered'],op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')


In [8]:
for i in np.nditer(arr3):
    print(i)

1
2
3
4
5
6


In [9]:
for j,d in np.ndenumerate(arr3):
    print(j,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6


# copy vs View in numpy

#    copy 
copy own tne data.<br>the copy of an array is a new array.<br>the change made in the copy data does not reflect in the original array

# view
the view does not own data.<br>
a view of the original array.<br>any changes made to the view will affect the original array.and any change made to the original array will affect the view

In [14]:
# copy
arr=np.array([1,2,3,4,5,6])
co=arr.copy()
print('original:',arr)
print('copy:',co)

arr[2]=10
print('original after change:',arr)
print('copy:',co)             

original: [1 2 3 4 5 6]
copy: [1 2 3 4 5 6]
original after change: [ 1  2 10  4  5  6]
copy: [1 2 3 4 5 6]


In [16]:
# view
varr=np.array([1,2,3,4,5,6])
vi=varr.view()
print('original:',varr)
print('view:',vi)

varr[2]=10
print('original after change:',varr)
print('view:',vi)             

original: [1 2 3 4 5 6]
view: [1 2 3 4 5 6]
original after change: [ 1  2 10  4  5  6]
view: [ 1  2 10  4  5  6]


# Join & Split function

# join
join array: joining means putting contents of two or more arrays in a single array<br>
for mearge it has 2 method <Br>
1.np.concatenate((var1,var2),axis) axis used in only multidiamentional array<br>
2.np.stack((var1,var2),axis) it works among axis<br>
if you put "h" in front of stack then row alon mearge,"v" along column,"d" for hight along mearge

In [18]:
j1=np.array([1,2,3,4,5])
j2=np.array([7,8,9])
jo=np.concatenate((j1,j2))
print(jo)

[1 2 3 4 5 7 8 9]


In [20]:
j3=np.array([[1,2,],[3,4]])
j4=np.array([[5,7],[8,9]])
joo=np.concatenate((j3,j4),axis=0)
print(joo)

[[1 2]
 [3 4]
 [5 7]
 [8 9]]


In [25]:
jos=np.stack((j3,j4),axis=1)
print(jos)

[[[1 2]
  [5 7]]

 [[3 4]
  [8 9]]]


In [24]:
jor=np.hstack((j3,j4))
print(jor)
print()

joc=np.stack((j3,j4))
print(joc)
print()
joh=np.stack((j3,j4))
print(joh)


[[1 2 5 7]
 [3 4 8 9]]

[[[1 2]
  [3 4]]

 [[5 7]
  [8 9]]]

[[[1 2]
  [3 4]]

 [[5 7]
  [8 9]]]


# split array
it spllit np.array_split(var,count,axis) it gives result in list form the you can get single array by indexing

In [28]:
ap=np.array([1,2,3,4,5])
s=np.array_split(ap,2)
print(s)
print(s[0])

[array([1, 2, 3]), array([4, 5])]
[1 2 3]


In [29]:
s2=np.array([[1,2,],[3,4]])
s3=np.array_split(s2,2)
print(s3)

[array([[1, 2]]), array([[3, 4]])]
