In [28]:
import numpy as np

# Matrix
it perform all matrix operation

In [29]:
mat=np.matrix([[1,2,3],[1,2,3]])
print(mat)
print(type(mat))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [30]:
mat2=np.matrix([[1,2,3],[1,2,3]])
print('addition: \n',mat+mat2)
print('substraction: \n',mat-mat2)


addition: 
 [[2 4 6]
 [2 4 6]]
substraction: 
 [[0 0 0]
 [0 0 0]]


for multiplication in matrix we use .dot() for multiply

In [31]:
mat3=np.matrix([[1,2],[1,2]])
print('multiplication: \n',mat3.dot(mat3))

multiplication: 
 [[3 6]
 [3 6]]


## functions in matrix

### 1.Transpose: np.transpose()  (shortcut:var.T)
### 2.Swapaxes: np.swapaxes(var,change,change)
### 3.Inverse: np.linalg.inv()
### 4.Power: np.linalg.matrix_power(var,n)
### 5.Determinate: np.linalg.det()

In [32]:
mat4=np.matrix([[1,2],[3,4]])
print('1.Transpose:\n', np.transpose(mat))
print('2.Swapaxes:\n', np.swapaxes(mat4,1,0))
print('3.Inverse: \n',np.linalg.inv(mat4))
print('4.Power: \n',np.linalg.matrix_power(mat4,2))
print('5.Determinate: \n',np.linalg.det(mat4))

1.Transpose:
 [[1 1]
 [2 2]
 [3 3]]
2.Swapaxes:
 [[1 3]
 [2 4]]
3.Inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
4.Power: 
 [[ 7 10]
 [15 22]]
5.Determinate: 
 -2.0000000000000004
