In [1]:
import numpy as np


# Search Array
Search an array for certain value, and return the indexes that get a match.<br>
for seach we use where key word<br>
you can also search by passing aritmetic operation <br>
its return index of element

In [2]:
arr=np.array([1,4,2,3,4,5,644,4,7,8])
x=np.where(arr==4)
print(x)

(array([1, 4, 7]),)


# search sorted array
which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.<br>
it uses np.searchsorted(var,element,side) function we can pass full ins in it and we can aslo pass where its search.

In [4]:
arr1=np.array([1,2,4,6,7,9])
s=np.searchsorted(arr1,[3,5,8])  #side is left by default
s

array([2, 3, 5])

# Sort Array
ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending. <br>
it uses np.sort(var)

In [6]:
arr2=np.array([1,4,3,55,77,99,2,3,4,5,644,4,7,8])
print(np.sort(arr2))

[  1   2   3   3   4   4   4   5   7   8  55  77  99 644]


# Filter Array
Getting some elements out of an existing array and crating a new array out of them.<br>
for filter arry we pass list with true and false with same indexing that we want.

In [8]:
fil=[True,False,False,True,True,False]
arr3=arr1[fil]
print(arr3)

[1 6 7]


# Arithmatic Function

## Shuffle
it shuffle the array with using random module,<br>np.random.shuffle(var)

In [17]:
arr4=np.array([1,2,3,4,5,6,7])
np.random.shuffle(arr4)
print(arr4)

[5 7 3 1 2 6 4]


## Unique
it returns unique means not repeated data in array for index number make return_index true and also we count frequency passing return_count true.<br>
np.unique(var,return_index,return_counts)

In [19]:
arr5=np.array([1,2,3,4,5,6,7,4,5,3,2,4,2,2,2,])
un=np.unique(arr5,return_index=True,return_counts=True)
print(un)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6]), array([1, 5, 2, 3, 2, 1, 1]))


# Resize
it changes array size<br>
np.resize(var,(new size))

In [20]:
arr6=np.array([1,2,3,4,5,6])
re=np.resize(arr6,(3,2))
re

array([[1, 2],
       [3, 4],
       [5, 6]])

# Flatten & Ravel
both conver 2d array in singal diamention array<Br>
it has row major order anc column major order <br>
order{C,F,A,K}<br>
C---- means to flatten in row major(c style) order<br>
F---- means to flatten in column major (fortran style)order<br>
A---- means to flatten in column major if 'a' is Fortran *contiguous* in memory, row major order otherwise.<br>
K---- means to flatten 'a' in the order the elements occur in memory 


<br><br>
by default it is 'C'

In [22]:
print('Flatten:',re.flatten(order='F'))
print('Ravel:',np.ravel(re,order='F'))

Flatten: [1 3 5 2 4 6]
Ravel: [1 3 5 2 4 6]


# Insert
insert data in array<br>
np.insert(var,position,value)     you can pass many position& multiple data<br>
in multidimentional array you have to pass axis<br>
we can use also append function
in insert you can not insert different data type but append can add it

In [24]:
arr7=np.array([1,2,3,4,5,6])
ins=np.insert(arr7,(3,4),33)
ins

array([ 1,  2,  3, 33,  4, 33,  5,  6])

# Delete 
it delete value from array<br>
np.delete(var,position)

In [27]:
a=np.delete(arr7,3)
print(a)

[1 2 3 5 6]
